version: "3.4"

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper

  mongo-container:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  mysql-container:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_container:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=techbankRoot
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql-container
    depends_on: 
      - mysql-container

volumes:
  mongodb_data_container:
    driver: local
  mysql_data_container:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  techbankNet:
    driver: bridge
